name: RushMe
author: tips48
main: com.tips48.rushMe.RushMe
version: 0.1
depend: [Spout]
commands:
    RushMe:
       description: Main command for RushMe
permissions:
    RushMe.create:
       description: Access to the /RushMe create command
       default: op
    RushMe.delete:
       description: Access to the /RushMe delete command
       default: op